### ISSUE TITLE
Build failing on Arch Linux

### ISSUE THREAD

**Issue by blueberry** [gpu/JOCLBlast#1]
Hi,

The build is failing in my Arch Linux with gcc 5.3 (very recent versions of all software). JOCL version is built from the commit 862f2ab. I used the latest development branch of CLBlast and installed it on my system without problems.

I successfully did the cmake-gui stuff, and, as per JOCL instructions, invoked make. This is the beginning of the wall of basically the same error:

 JOCLBlast.build make  
[ 75%] Built target JOCLCommon
[ 87%] Building CXX object CMakeFiles/JOCLBlast_0_0_1-linux-x86_64.dir/src/main/native/JOCLBlast.cpp.o
In file included from /usr/include/c++/5.3.0/cstdint:35:0,
                 from /home/dragan/workspace/java/jocl/JOCLCommon/src/main/native/ConversionsCL.hpp:32,
                 from /home/dragan/workspace/java/jocl/JOCLBlast/src/main/native/JOCLBlast.cpp:41:
/usr/include/c++/5.3.0/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /home/dragan/workspace/java/jocl/JOCLBlast/src/main/native/JOCLBlast.cpp:41:0:
/home/dragan/workspace/java/jocl/JOCLCommon/src/main/native/ConversionsCL.hpp: In function ‘bool initNativeGenericFixedSize(JNIEnv_, JavaArrayType, NativeType_&, bool)’:
/home/dragan/workspace/java/jocl/JOCLCommon/src/main/native/ConversionsCL.hpp:58:23: error: ‘nullptr’ was not declared in this scope
     if (javaObject == nullptr)
                       ^
/home/dragan/workspace/java/jocl/JOCLCommon/src/main/native/ConversionsCL.hpp:65:25: error: ‘nullptr’ was not declared in this scope
     if (nativeObject == nullptr)
                         ^
/home/dragan/workspace/java/jocl/JOCLCommon/src/main/native/ConversionsCL.hpp:74:67: error: ‘nullptr’ was not declared in this scope
             (JavaType_)env->GetPrimitiveArrayCritical(javaObject, nullptr);
                                                                   ^
/home/dragan/workspace/java/jocl/JOCLCommon/src/main/native/ConversionsCL.hpp: In function ‘bool releaseNativeGenericFixedSize(JNIEnv_, NativeType*&, JavaArrayType, bool)’:
/home/dragan/workspace/java/jocl/JOCLCommon/src/main/native/ConversionsCL.hpp:121:23: error: ‘nullptr’ was not declared in this scope
     if (javaObject == nullptr)
                       ^

**Comment by gpu** [comment]
This is likely related to https://github.com/gpu/JOCL/issues/1#issue-145435807 : It seems that (on non-windows-systems), C++ 11 must explicitly be enabled. I did this for JOCL, but not yet for JOCLBlast, this should be fixed with the above commit.

(I also added it for JOCLBLAS, assuming that it will be the same there. In fact, the JOCLCommon project contains some C++11 features. Particularly, the use of `nullptr` instead of `NULL` and `0`)

**Comment by blueberry** [comment]
Thanks. I'll test is as soon as the JOCL Sizeof problem is solved and I can build the latest JOCL. BTW, the requirement for this library is JOCL-RC01-SNAPSHOT, or it could work with JOCL-RC00?

**Comment by gpu** [comment]
Yes, it will need the snapshot version, because it has to load the CLBlast library before the JOCLBlast library can be loaded, and this functionality was not yet available in RC00.

I hope once these points (particularly the Sizeof issue) are settled, I can create a new release.

**Comment by blueberry** [comment]
I can confirm that this works now.
