### ISSUE TITLE
New version of CLBlast 1.1.0

### ISSUE THREAD

**Issue by blueberry** [gpu/JOCLBlast#10]
@gpu CLBlast 1.1.0 has been released.

**Comment by CNugteren** [comment]
Note that there is one new routine in the API (see [changelog](https://github.com/CNugteren/CLBlast/releases)):
SIM2COL/DIM2COL/CIM2COL/ZIM2COL/HIM2COL

**Comment by gpu** [comment]
Thanks for this heads-up, I'll prepare the update ASAP. 
The new routine should already be covered by the code generator, but I'll check this.

**Comment by gpu** [comment]
@blueberry @amherag : The tag for building the native libraries for 1.1.0 is at https://github.com/gpu/JOCLBlast/releases/tag/1.1.0-RC00

**Comment by blueberry** [comment]
@gpu @amherag I'll be able to compile it next week. Sorry for the delay.

**Comment by amherag** [comment]
@gpu @blueberry Hmm... the jar says 1.0.2 instead of 1.1.0. The pom.xml still has version 1.0.2 too. I'll say it's okay to just rename the jar to 1.1.0, so here's the file.

[jocl-blast-1.1.0-SNAPSHOT.jar.zip](https://github.com/gpu/JOCLBlast/files/1393705/jocl-blast-1.1.0-SNAPSHOT.jar.zip)

**Comment by blueberry** [comment]
@gpu 
Here's the linux version: 
[jocl-blast-1.1.0-SNAPSHOT.zip](https://github.com/gpu/JOCLBlast/files/1395942/jocl-blast-1.1.0-SNAPSHOT.zip)

@gpu @amherag @CNugteren  Thank you all!

**Comment by gpu** [comment]
Indeed, the version number in the POM is not yet updated, but this should not affect the remaining parts of the release - it's a `SNAPSHOT` after all. I'll do the update and release ASAP.

**Comment by gpu** [comment]
The new version has been released, and will soon be in Maven Central at 
```
<dependency>
    <groupId>org.jocl</groupId>
    <artifactId>jocl-blast</artifactId>
    <version>1.1.0</version>
</dependency>
```

Thanks again to @amherag @blueberry and @CNugteren !
