### ISSUE TITLE
Update to the newest CLBlast

### ISSUE THREAD

**Issue by blueberry** [gpu/JOCLBlast#2]
The newest commits in the development branch of CLBlast contain implementation of xASUM and a few other routines that were missing in the previous version.

Can you please generate an updated version of JOCLBlast? I would like to implement a JOCLBlast-based engine in Neanderthal, and test JOCLBlast with a lot of existing tests.

**Comment by gpu** [comment]
Thanks for this heads up. I have updated based on the current version of CLBlast 

(Some questions related to https://github.com/gpu/JOCL/issues/6 may arise here: It should somehow be made clear which version of JOCLBlast belongs to which version of CLBlast. Right now, this is not as critical, but once the first version is about to be available in Maven Central, it becomes crucial).

**Comment by blueberry** [comment]
Thanks.

Regarding the versioning, I think the best is to keep it 0.x.y, where the documentation gives a CLBlast commit or date that JOCLBlast is based on, then do frequent releases, even if not all platform binaries are there, and state clearly which platforms are supported in which version. So far, we can cover windows and linux, and, if the build is made straightforward on OSX, I can try to cover this as well, although I am not sure whether it will succeed, since my old mac does NOT support any OpenCL.

**Comment by gpu** [comment]
There are contributions for JOCL on Mac, but am not sure whether someone could contribute the JOCLBlast binaries for Mac. 

BTW, regarding the update: I only ran the "basic binding test". Creating more test cases is also still on my TODO list.

**Comment by blueberry** [comment]
I have lots of hand written test cases (more than 800) in Neanderthal, so I think this could cover CLBlast well, only if I make it work.
